default: &defaults
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *defaults
  database: gestao-escolar_development

test:
  <<: *defaults
  database: gestao-escolar_test

production:
  <<: *defaults
  database: gestao-escolar_production